#cloud-config
#https://learn.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-automate-vm-deployment
package_upgrade: true
packages:
  - nginx
  - nodejs
  - npm
  - certbot
  - python3-certbot-nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        server_name ugly.hschaletzky.de;
        location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
  - path: /code/index.js
    content: |
      var express = require('express')
      var app = express()
      var os = require('os');
      app.get('*', function (req, res) {
        res.send('Hello World from host ' + os.hostname() + '!')
      })
      app.listen(3000, function () {
        console.log('Hello world app listening on port 3000!')
      })
  - path: /code/package.json
    content: |
      {
        "name": "boilerplatebackend",
        "version": "1.0.0",
        "description": "",
        "main": "index.js",
        "scripts": {
          "test": "echo \"Error: no test specified\" && exit 1"
        },
        "dependencies": {
          "express": "^4.18.2"
        },
        "author": "HannesSchaletzky",
        "license": "MIT"
      }

runcmd:
  # setup backend
  - npm i -g pm2
  # enable firewall
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  - ufw enable
  - ufw status

  # reboot to tackle:
  #   The currently running kernel version is not the expected kernel version 6.2.0-37-generic.
  #   Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting. [Return]
  - sudo reboot

  # after reboot:
  # cd /code
  # npm install
  # pm2 start /code/index.js
  # certbot install for ugly.hschaletzky.de
  # sudo service nginx restart
  # add private key to id_rsa for git
