#cloud-config
# Add groups to the system
# The following example adds the 'admingroup' group with members 'root' and 'sys'
# and the empty group cloud-users.
groups:
  - admingroup: [root, sys]
  - cloud-users

# Add users to the system. Users are added after groups are added.
# Note: Most of these configuration options will not be honored if the user
#       already exists. Following options are the exceptions and they are
#       applicable on already-existing users:
#       - 'plain_text_passwd', 'hashed_passwd', 'lock_passwd', 'sudo',
#         'ssh_authorized_keys', 'ssh_redirect_user'.
users:
  - default
  - name: barfoo
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    system: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkYvjd4ZqlM57Vsm6p6GF7C47LdOxhqgH+Cn42xmHLt+PxdvjfT0kbST4ucNXX5YjA1VmebmnTMNXFLUGRj0M+Ke6CHH+RevdSxqGhFeIhjS9b9nSfVOJyRT/ISkJIPc2gzsXxikIEqpN63zDaRa4YoNvJuiIETsnjpJk8ORCSsGbMyxh4sjW9khcDI4QbNKl0xWMyJTekbMJAj1A2WZc+Oc+ruVZFd4igqLhoIDHxh8Rzqa3yvthGjGLblK6kz6Lwpu28PGQcxxsPp0nr0TGBhG69HjO3Vvax6fQfTFoSFJsk3e7caI9l53oj4jXoIWghLJciqxs5CXuTv80w6MzfnHXu/znwHC96pwQBOl7OgQsmPtaoivtH82+0x+VE36ByliPfXHqkOT95UA110YTBGfodu0uTbSDjWQJu7Pj6KHI7cTNPLRYmsx43GRGmh7S3SsMJ7shV/HORSADkjRih7HaSHdwMVhVueFrLYDQeov+yNybHqbf1LZVfRKG4QW0= info@hschaletzky.com
