# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

#cloud-config
groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2Xhke4r2wCnu4RykkIZP5GnBMcoSTY0N8Fwt9/20wxbE0zJWzSsp41wHG7Ks+qWEzXU6srzWjT/WEmBlwneYkj1Av36xnUHPN3bCj/nbkGlnZkOyOTbR2EXLVTWORVEL4YjMrRO60vuG8R4/lWlEu9r/r7Sb9eng/aZtnqO5FthLgwtpI768Ns4joGW4hgvFOLPcOYqk3T/v7hnqLqaOYR3sGIJfCOT/VqlrFyIh0+Fdd94gCTMpsI8GbZWoyKh1FCsknpN8qL2Lxx30Y7ShwzDEZcmyzh1YlsY2Ohp3BKaU4WU1ut0RnWpIouEq4KGCaP4nJnkFaZI+gIGm12u1+1HQGJmwFLDcFYBzqAW0Vv62cRWFSqwpbXRIopnAjjL/U+CSIfIjejbf/cAZGNx+ds7gKlaZP/Skv3zNP+R9pPQVED55ihQ47niOmAD32O6vxo+KCkocPdMvY3ehJSRHgBROxHCaQSnIj5palKdMImqXaCDUiR/zMNSPWCSI793c= hannesschaletzky@HannesMlservice

runcmd:
  - sudo apt-get update
  - sudo apt install apache2 -q -y
  - sudo curl https://raw.githubusercontent.com/hashicorp/learn-terraform-digitalocean-droplet/main/app/index.php -O
  - sudo rm /var/www/html/index.html
  - sudo mv index.php /var/www/html
  - sudo systemctl restart apache2
